version: '3.8'
services:
  postgres:
    image: postgres:16.6
    container_name: goomerDB
    ports:
      - "5440:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
